# -*- coding: utf-8 -*-
"""Lab01-SP23BCS083.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7sVSPdMzZNvOK-x-leIE4SDX71uFYcR

## Activity 01
"""

num = input("Enter your number")
if int(num) % 2 == 0:
    print("even")
else:
    print("odd")

"""#Activity 02

"""

sum = 0
s = input("Enter your number\t")
num = int(s)
while num != 0:
    sum += num
    s = input("Enter your number\t")
    num = int(s)
print("Sum = ", sum)

"""# Activity 3

"""

from math import sqrt
divisor = 2
s = input("Enter your number\t")
num = int(s)
while(divisor <= sqrt(num)):
    if(num % divisor == 0):
        print("Not prime")
        break
    divisor += 1
else:
    print("Prime")

"""# Activity 4"""

sum = 0
for i in range(5):
  num = input("Enter your number\t")
  n = int(num)
  sum += n
print("Sum =", sum)

"""# Activity 5"""

i = 1
sum = 0
while i < 11:
  sum += i
  i += 1
print("Sum =",sum)

"""# Activity 6"""

#!/usr/bin/env python3

name  =  input('What  is  your  name?  ')
print('Hello ' + name)

job  =  input('What  is  your  job?  ')
print('Your  job  is  '  +  job)

num  =  input('Give  me  a  number?  ')
print('You said: ' + str(num))

"""# Activity 7"""

import random

MINIMUM = 1
MAXIMUM = 9
NUMBER = random.randint(MINIMUM, MAXIMUM)
GUESS = None
ANOTHER = None
TRY = 0
RUNNING = True

print("Alright...")

while RUNNING:
    GUESS = input("What is your lucky number? ")

    if GUESS.lower() == "exit":
        print("Better luck next time.")
        break

    if not GUESS.isdigit():
        print("Please enter a valid number.")
        continue

    GUESS = int(GUESS)

    if GUESS < NUMBER:
        print("Wrong, too low.")
    elif GUESS > NUMBER:
        print("Wrong, too high.")
    elif GUESS == NUMBER:
        print(f"Yes, that's the one, {NUMBER}.")
        if TRY < 2:
            print(f"Impressive, only {TRY} tries.")
        elif 2 <= TRY < 10:
            print(f"Pretty good, {TRY} tries.")
        else:
            print(f"Bad, {TRY} tries.")
        RUNNING = False

    TRY += 1

"""# Lab Task 01"""

num = input("Enter your number\t")
rev_num = ""
i = len(num) - 1
while i >= 0:
  rev_num += num[i]
  i -= 1
print("reverse num =", rev_num)

"""# Lab task 02"""

even_sum = 0
odd_sum = 0
print("Enter integers one per line (enter 0 to finish):")
while True:
    num = int(input())
    if num == 0:
        break
    if num % 2 == 0:
        even_sum += num
    else:
        odd_sum += num
print(f"Sum of even numbers: {even_sum}")
print(f"Sum of odd numbers: {odd_sum}")

"""# Lab task 03"""

# iterative version
n = int(input("Enter number of terms: "))
a = 0
b = 1
if n >= 1:
    print(a, end=" ")
if n >= 2:
    print(b, end=" ")
for i in range(2, n):
    c = a + b
    print(c, end=" ")
    a = b
    b = c
print()

# recursive version
def fib(n):
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)

n = int(input("Enter number of terms: "))
for i in range(n):
    print(fib(i), end=" ")
print()

"""# Lab task 04"""

marks = int(input("Enter marks (1-100): "))

if marks >= 1 and marks <= 100:
    if marks < 50:
        print("Grade F")
    elif marks <= 60:
        print("Grade E")
    elif marks <= 70:
        print("Grade D")
    elif marks <= 80:
        print("Grade C")
    elif marks <= 90:
        print("Grade B")
    else:
        print("Grade A")
else:
    print("Invalid marks! Please enter marks between 1 and 100")

"""# Lab task 05"""

# iterative
n = int(input("Enter a number: "))
fact = 1
for i in range(1, n + 1):
    fact *= i
print(f"Factorial of {n} is {fact}")

# recursive
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

n = int(input("Enter a number: "))
result = factorial(n)
print(f"Factorial of {n} is {result}")